### ISSUE TITLE
Hero - Sanitize input 

### ISSUE THREAD

**Issue by marceloglacial** [brito-ca/brito-website#32]

**Comment by marceloglacial** [comment]
Create a sanitize component

**Comment by DercilioFontes** [comment]
Acabei perguntando para o Bing e ele sugeriu sanitize-html e funcionou. Criei um branch. Depois olha lá https://github.com/brito-ca/brito-website/tree/sanitize-try
![Screenshot 2023-03-30 at 10 46 52 PM](https://user-images.githubusercontent.com/20172847/229010698-2127860e-fe05-4489-984f-9561a65ab3ad.png)
