### ISSUE TITLE
Review Mockups Styles

### ISSUE THREAD

**Issue by marceloglacial** [brito-ca/brito-website#36]

**Comment by DercilioFontes** [comment]
- [ ] "About/Join us/Contact" nav **VS**  "About us/Join us/Contact us" sections --> Shouldn't it be all the same?
![Screenshot_2023-03-07_at_9 10 28_PM](https://user-images.githubusercontent.com/20172847/223914242-3a4b93a5-2c2c-4674-a9f1-fff7908d4a90.png)
![Screenshot_2023-03-07_at_9 10 42_PM](https://user-images.githubusercontent.com/20172847/223914255-5257ef06-863d-4083-8d5e-a99963c64752.png)
![Screenshot_2023-03-07_at_9 10 52_PM](https://user-images.githubusercontent.com/20172847/223914275-b37abae3-ecc1-4948-b039-7001b6e97e2e.png)
![Screenshot_2023-03-07_at_9 10 47_PM](https://user-images.githubusercontent.com/20172847/223914262-23ea651b-7eff-404a-8fbb-d34ddf9babf2.png)

**Comment by DercilioFontes** [comment]
- [ ] Buttons: Style guide **VS** Desktop **VS** Mobile --> They are not uniform. How is the proper styles for hover and active (clicked)?
Style guide:
![Screenshot 2023-03-08 at 11 12 56 PM](https://user-images.githubusercontent.com/20172847/223915254-93b3ad95-ff5d-4a94-a77b-4b57b505f5e7.png)
Desktop:
![Screenshot 2023-03-08 at 11 15 32 PM](https://user-images.githubusercontent.com/20172847/223915432-9e4c5bd5-5848-47e7-b366-62682689ebfa.png)
![Screenshot 2023-03-08 at 11 15 43 PM](https://user-images.githubusercontent.com/20172847/223915448-bc1bf7c8-6be5-430f-afd0-1c8236753b33.png)
Mobile:
![Screenshot 2023-03-08 at 11 16 02 PM](https://user-images.githubusercontent.com/20172847/223915460-022d26e4-e4f7-4ac6-ba0c-1de8f873ecbc.png)
![Screenshot 2023-03-08 at 11 16 13 PM](https://user-images.githubusercontent.com/20172847/223915464-0fae10e9-dd15-4cfe-b8d9-93f5a80d8556.png)

**Comment by DercilioFontes** [comment]
> [ ] "About/Join us/Contact" nav **VS** "About us/Join us/Contact us" sections --> Shouldn't it be all the same?

It was defined as "About/Join us/Contact" and "About us/Join us/Contact us" sections. (Roger, meeting 2023-03-09)

**Comment by Estefanieschuster** [comment]
Buttons: Style guide VS Desktop VS Mobile --> They are not uniform. How is the proper styles for hover and active (clicked)?
Thank you for catching that. I have now updated accordingly with the style guide.

**Comment by DercilioFontes** [comment]
@marceloglacial, assigning the ticket to you to review.

I sent a PR for topic 1.

For 2, we have only updates to the form, mainly for mobile. It seems to me.

**Comment by rfyujisato** [comment]
Follow the differences in the footer:
Desktop:
      Title: h5
      Links: b2
      Copyright: default
Mobile:
      Title: h6
      Links: b6
      Copyright: b7
