### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by DercilioFontes** [brito-ca/brito-website#52]
- [x] install translation plugin
- [x] add Portuguese homepage
- [x] add French homepage
- [x] add english homepage 
- [x] setup API endpoint 
- [x] add code implementation

Note: all English if the translation is not available yet

**Comment by marceloglacial** [comment]
HomePage endpoint: https://brito.it/wp-json/wp/v2/homepage

**Comment by DercilioFontes** [comment]
@marceloglacial, I'm going to implement this ticket.
