### ISSUE TITLE
Fix style for dropdown on Safari

### ISSUE THREAD

**Issue by DercilioFontes** [brito-ca/brito-website#77]
![Screenshot 2023-04-07 at 4 41 49 PM](https://user-images.githubusercontent.com/20172847/230676368-c67cd870-3638-44e9-ab3d-a4b0fd69193b.png)

**Comment by douglasvinicio** [comment]
Fixed

**Comment by DercilioFontes** [comment]
@douglasvinicio, I checked. It is fixed, but the city field is hard to see. I wonder if it is related. 
![Screenshot 2023-04-10 at 9 23 45 PM](https://user-images.githubusercontent.com/20172847/231031121-f30dbc30-0b7b-4162-b91f-4e74e7b0bd7a.png)

**Comment by DercilioFontes** [comment]
I see in the first picture that it is not related. I'll create a new ticket.
