### ISSUE TITLE
Add page icon

### ISSUE THREAD

**Issue by DercilioFontes** [brito-ca/brito-website#92]
It is still the Vercel icon
![image](https://user-images.githubusercontent.com/20172847/232036480-6284b1c5-e55c-44a6-a067-e71f4b96c740.jpeg)

**Comment by rrrainville** [comment]
Qual o icone a ser usado?

**Comment by DercilioFontes** [comment]
Pode usar a bandeirinha ou logo.
![image](https://user-images.githubusercontent.com/20172847/232181741-c92687e8-8dc7-40a9-b60a-4b7e017e15b8.jpeg)
![image](https://user-images.githubusercontent.com/20172847/232181745-2ece5bbd-eb70-4b35-8f4b-d7f3ac4116d5.jpeg)

**Comment by DercilioFontes** [comment]
I sent a PR for that one: https://github.com/brito-ca/brito-website/pull/97

Used the flag.
![Screenshot 2023-04-15 at 7 36 39 PM](https://user-images.githubusercontent.com/20172847/232258589-7a10e418-a769-458c-bf0c-bb7c14eafd26.png)

![Screenshot 2023-04-15 at 7 31 33 PM](https://user-images.githubusercontent.com/20172847/232258591-45c9115d-9856-49ce-854c-dcdd321f7025.png)
